#!/bin/bash
unset IFS
set -eufo pipefail

echo "\$#: $#"
echo "\$1: $1"

if [ "$#" -gt 0 ]; then
    if [ "$1" = '-d' ]; then
        set +x
    fi
fi

#
# Sync changes between local and remote for current git branch
#

git fetch --all >/dev/null

git add . >/dev/null

if [ -n "$(git status --porcelain)" ]; then
    git commit -m 'up' >/dev/null
    git pull >/dev/null
    git push >/dev/null 2>&1
fi

git fetch --tags >/dev/null
git push --tags >/dev/null
