#!/bin/bash
unset IFS
set -xeufo pipefail

#
# Sync changes between local and remote for current git branch
#

git fetch --all >/dev/null

git add . >/dev/null

if [ -n "$(git status --porcelain)" ]; then
    git commit -m 'up' >/dev/null
    git pull >/dev/null
    git push 2>&1 >/dev/null
fi

git fetch --tags >/dev/null
git push --tags >/dev/null
