#!/bin/bash
unset IFS
set -eufo pipefail

usage() {
    printf "Usage: $0 [OPTIONS]\n\n"
    printf -- "-h\tShow usage menu\n"
    printf -- "-d\tEnable debug mode\n"
}

STDERR_TARGET='/dev/null'
STDOUT_TARGET='/dev/null'

enable_debugging() {
    STDERR_TARGET=2
    STDOUT_TARGET=1
    set -x
}

if [ "$#" -gt 0 ]; then
    ARG="$1"

    case "$ARG" in
        '-h')
            usage
            exit
            ;;
        '-d')
            enable_debugging
            ;;
        *)
            usage
            exit 1
            ;;
    esac
fi

#
# Sync changes between local and remote for current git branch
#

git fetch --all >"$STDOUT_TARGET"

git add . >"$STDOUT_TARGET"

if [ -n "$(git status --porcelain)" ]; then
    git commit -m 'up' >"$STDOUT_TARGET"
    git pull >"$STDOUT_TARGET"
    git push >"$STDOUT_TARGET" 2>"$STDERR_TARGET"
fi

git fetch --tags >"$STDOUT_TARGET"
git push --tags >"$STDOUT_TARGET"
